import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

// const roboto = Roboto({
//   weight: ["400", "500", "700"],
//   variable: "--font-roboto",
//   subsets: ["latin"],
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      // 1. Added "dark" to force Shadcn's dark CSS variables
      className={`dark ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* 2. Added bg-background and text-foreground to apply the dark colors to the whole page */}
      <body className="min-h-full flex flex-col bg-background text-foreground font-sans">
        {children}
      </body>
    </html>
  );
}
