import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Inter, Orbitron, Share_Tech_Mono } from "next/font/google";
import { SocketInit } from "@/components/SocketInit"

const inter = Inter({ subsets: ["latin"] });

const orbitron = Orbitron({
  subsets: ["latin"],
  variable: "--font-orbitron",
});

const shareTechMono = Share_Tech_Mono({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-share-tech",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`dark ${inter.className} ${orbitron.variable} ${shareTechMono.variable} ${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      {/* THE FIX: 
        1. Changed 'min-h-full' to 'h-full' to rigidly lock the height.
        2. Added 'overflow-hidden' to prevent the document body from ever scrolling.
      */}
      <body className="h-screen overflow-hidden bg-background text-foreground font-sans">
        <SocketInit />

        <main className="h-full overflow-y-auto">
          {children}
        </main>
      </body>
    </html>
  );
}
