"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
// REMOVED: import { getDMRoomId } from "@multiplayer/shared" -> We no longer guess strings!
import { useSessionStore } from "@/store/sessionStore"
import { Button } from "@/components/ui/button"
import { MessageSquare, Loader2 } from "lucide-react"

import { useFriendStore } from "@/store/friendStore"
import { usePresenceStore } from "@/store/presenceStore"

import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"

export function FriendList() {
    // 1. Get the static array of accepted friends
    const friends = useFriendStore((state) => state.friends)
    const isHydrated = useFriendStore((state) => state.isHydrated)

    // 2. Get the real-time array of who is currently connected
    const onlineUsers = usePresenceStore((state) => state.onlineUsers)

    // Calculate how many friends are online for the badge
    const onlineFriendsCount = friends.filter(f => f.user.username && onlineUsers.includes(f.user.username)).length

    const router = useRouter();
    const currentUserId = useSessionStore((s) => s.userId);
    
    // NEW: Local state to prevent spam-clicking while the database provisions the room
    const [isNavigating, setIsNavigating] = useState(false);

    // ============================================================================
    // THE NEW SECURE DM ROUTER
    // ============================================================================
    const handleMessageFriend = async (friendId: string, friendUsername: string) => {
        if (!currentUserId || !friendId || isNavigating) return;

        setIsNavigating(true);

        try {
            // 1. Ask the Express Backend to Get or Create the relational Room
            const response = await fetch("/api/rooms/dm", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ targetUserId: friendId })
            });

            if (!response.ok) {
                throw new Error("Failed to provision DM room");
            }

            const data = await response.json();
            
            // 2. We now have a true relational UUID generated by Prisma
            const realRoomId = data.roomId;

            // 3. Push to the UUID and pass metadata via URL so RoomScreen doesn't have to fetch it
            router.push(`/room/${realRoomId}?type=DIRECT&title=${encodeURIComponent(friendUsername)}`);
        } catch (error) {
            console.error("DM Routing Error:", error);
            // Optionally, add a toast notification here if it fails
        } finally {
            setIsNavigating(false);
        }
    };

    return (
        <Card className="h-full">
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-4">
                <CardTitle className="text-lg">My Friends</CardTitle>
                <Badge variant="default" className="bg-green-500 hover:bg-green-600">
                    {onlineFriendsCount} Online
                </Badge>
            </CardHeader>
            <CardContent>
                <ScrollArea className="h-[300px] pr-4">
                    <div className="space-y-2">
                        {
                            !isHydrated ? (
                                <p className="text-sm text-muted-foreground text-center py-8 animate-pulse">
                                    Loading friends...
                                </p>
                            ) : friends.length === 0 ? (
                                <p className="text-sm text-muted-foreground text-center py-8">
                                    You haven't added any friends yet.
                                </p>
                            ) : (
                                friends.map((friend) => {
                                    const isOnline = friend.user.username ? onlineUsers.includes(friend.user.username) : false;
                                    
                                    // Fallback just in case username is null in DB
                                    const displayUsername = friend.user.username || friend.user.name || "Friend";

                                    return (
                                        <div
                                            key={friend.friendshipId}
                                            className="flex items-center justify-between p-3 rounded-lg border bg-card hover:bg-accent transition-colors"
                                        >
                                            <div>
                                                <p className="font-medium text-sm">
                                                    {friend.user.username}
                                                </p>
                                                <p className="text-xs text-muted-foreground">
                                                    {friend.user.name}
                                                </p>
                                            </div>

                                            <div className="flex items-center gap-3">
                                                <div className="flex items-center gap-2">
                                                    <span className="text-xs text-muted-foreground">
                                                        {isOnline ? "Online" : "Offline"}
                                                    </span>
                                                    <div
                                                        className={`h-2.5 w-2.5 rounded-full ${isOnline
                                                            ? "bg-green-500"
                                                            : "bg-zinc-300 dark:bg-zinc-700"
                                                            }`}
                                                    />
                                                </div>

                                                {/* THE UPDATED MESSAGE BUTTON */}
                                                <Button
                                                    size="sm"
                                                    variant="secondary"
                                                    disabled={isNavigating}
                                                    onClick={() => handleMessageFriend(friend.user.id, displayUsername)}
                                                >
                                                    {isNavigating ? (
                                                        <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                                                    ) : (
                                                        <MessageSquare className="h-4 w-4 mr-2" />
                                                    )}
                                                    {isNavigating ? "Routing..." : "Message"}
                                                </Button>
                                            </div>
                                        </div>
                                    );
                                })
                            )
                        }
                    </div>
                </ScrollArea>
            </CardContent>
        </Card>
    )
}