"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { useSessionStore } from "@/store/sessionStore"
import { Button } from "@/components/ui/button"
import { MessageSquare, Loader2, UserMinus } from "lucide-react"
import { BACKEND_URL } from "@/lib/socket"

import { useFriendStore } from "@/store/friendStore"
import { usePresenceStore } from "@/store/presenceStore"

import { ScrollArea } from "@/components/ui/scroll-area"
import { Badge } from "@/components/ui/badge"

// Used to live wrapped in its own <Card> as a full tab panel. Now lives
// inside a Popover (triggered from the friends icon in LobbyHeader), so
// it's just the content — no outer Card/CardHeader chrome of its own.
export function FriendList() {
    // 1. Get the static array of accepted friends
    const friends = useFriendStore((state) => state.friends)
    const isHydrated = useFriendStore((state) => state.isHydrated)

    // 2. Get the real-time array of who is currently connected
    const onlineUsers = usePresenceStore((state) => state.onlineUsers)

    // Calculate how many friends are online for the badge
    const onlineFriendsCount = friends.filter(f => f.user.username && onlineUsers.includes(f.user.username)).length

    const router = useRouter();
    const currentUserId = useSessionStore((s) => s.userId);

    // NEW: Local state to prevent spam-clicking while the database provisions the room
    const [isNavigating, setIsNavigating] = useState(false);
    const [removingId, setRemovingId] = useState<string | null>(null);

    const handleRemoveFriend = async (friendshipId: string) => {
        if (removingId) return;
        setRemovingId(friendshipId);
        try {
            const res = await fetch(`${BACKEND_URL}/api/friends/remove`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                credentials: "include",
                body: JSON.stringify({ friendshipId }),
            });
            if (res.ok) {
                useFriendStore.getState().removeFriend(friendshipId);
            }
        } catch (error) {
            console.error("Failed to remove friend:", error);
        } finally {
            setRemovingId(null);
        }
    };

    // ============================================================================
    // THE NEW SECURE DM ROUTER
    // ============================================================================
    const handleMessageFriend = async (friendId: string, friendUsername: string) => {
        if (!currentUserId || !friendId || isNavigating) return;

        setIsNavigating(true);

        try {
            // 1. Ask the Express Backend to Get or Create the relational Room
            const response = await fetch(`${BACKEND_URL}/api/rooms/dm`, {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                credentials: "include",
                body: JSON.stringify({ targetUserId: friendId })
            });

            if (!response.ok) {
                throw new Error("Failed to provision DM room");
            }

            const data = await response.json();

            // 2. We now have a true relational UUID generated by Prisma
            const realRoomId = data.roomId;

            // 3. Push to the UUID and pass metadata via URL so RoomScreen doesn't have to fetch it
            router.push(`/room/${realRoomId}?type=DIRECT&title=${encodeURIComponent(friendUsername)}`);
        } catch (error) {
            console.error("DM Routing Error:", error);
            // Optionally, add a toast notification here if it fails
        } finally {
            setIsNavigating(false);
        }
    };

    return (
        <div className="space-y-3">
            <div className="flex items-center justify-between">
                <h3 className="font-medium text-sm">My Friends</h3>
                <Badge variant="default" className="bg-green-500 hover:bg-green-600">
                    {onlineFriendsCount} Online
                </Badge>
            </div>
            <ScrollArea className="h-72 pr-4">
                <div className="space-y-2">
                    {
                        !isHydrated ? (
                            <p className="text-sm text-muted-foreground text-center py-8 animate-pulse">
                                Loading friends...
                            </p>
                        ) : friends.length === 0 ? (
                            <p className="text-sm text-muted-foreground text-center py-8">
                                You haven't added any friends yet.
                            </p>
                        ) : (
                            friends.map((friend) => {
                                const isOnline = friend.user.username ? onlineUsers.includes(friend.user.username) : false;

                                // Fallback just in case username is null in DB
                                const displayUsername = friend.user.username || friend.user.name || "Friend";

                                return (
                                    <div
                                        key={friend.friendshipId}
                                        className="flex items-center justify-between p-3 rounded-lg border bg-card hover:bg-accent transition-colors"
                                    >
                                        <div>
                                            <p className="font-medium text-sm">
                                                {friend.user.username}
                                            </p>
                                            <p className="text-xs text-muted-foreground">
                                                {friend.user.name}
                                            </p>
                                        </div>

                                        <div className="flex items-center gap-3">
                                            <div className="flex items-center gap-2">
                                                <span className="text-xs text-muted-foreground">
                                                    {isOnline ? "Online" : "Offline"}
                                                </span>
                                                <div
                                                    className={`h-2.5 w-2.5 rounded-full ${isOnline
                                                        ? "bg-green-500"
                                                        : "bg-zinc-300 dark:bg-zinc-700"
                                                        }`}
                                                />
                                            </div>

                                            {/* THE UPDATED MESSAGE BUTTON */}
                                            <Button
                                                size="sm"
                                                variant="secondary"
                                                disabled={isNavigating}
                                                onClick={() => handleMessageFriend(friend.user.id, displayUsername)}
                                            >
                                                {isNavigating ? (
                                                    <Loader2 className="h-4 w-4 mr-2 animate-spin" />
                                                ) : (
                                                    <MessageSquare className="h-4 w-4 mr-2" />
                                                )}
                                                {isNavigating ? "Routing..." : "Message"}
                                            </Button>

                                            <Button
                                                size="icon"
                                                variant="ghost"
                                                disabled={removingId === friend.friendshipId}
                                                onClick={() => handleRemoveFriend(friend.friendshipId)}
                                                aria-label={`Remove ${displayUsername}`}
                                                className="text-muted-foreground hover:text-red-500"
                                            >
                                                {removingId === friend.friendshipId ? (
                                                    <Loader2 className="h-4 w-4 animate-spin" />
                                                ) : (
                                                    <UserMinus className="h-4 w-4" />
                                                )}
                                            </Button>
                                        </div>
                                    </div>
                                );
                            })
                        )
                    }
                </div>
            </ScrollArea>
        </div>
    )
}
